### ISSUE TITLE
Discord Invite Link update

### ISSUE THREAD

**Issue by NikhilMahana** [ScalantCommunity/ScalantWebsite#4]
The Discord Invite Link needs to be updated: https://www.scalant.in/discord

 Top of the website.
<img width="897" alt="image" src="https://user-images.githubusercontent.com/85444889/174066848-cdf16445-0255-4ea2-97a1-5ea0cd1d8b73.png">
Bottom of the Website.
<img width="904" alt="image" src="https://user-images.githubusercontent.com/85444889/174067109-103fdc87-c78d-42df-83a0-e508271192a1.png">

**Comment by dishant0406** [comment]
Completed
